Feat 04 course entity
lterrien/knp-taste pull request #6
Opened 2023-09-06 10:03 UTC by lterrien

2023-09-06 11:40 UTC, KevinArtus requested changes

2023-09-06 11:40 UTC, KevinArtus commented on apps/back/.env.dist
> +# DATABASE
It is already on other PR.
Perhaps it might better to do only one PR with all entities and fixtures

2023-09-06 11:40 UTC, KevinArtus commented on apps/back/composer.json
> +        "doctrine/doctrine-bundle": "^2.10",
It is already on other PR.

2023-09-06 11:40 UTC, KevinArtus commented on apps/back/config/bundles.php
> +    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
It is already on other PR.

2023-09-06 11:40 UTC, KevinArtus commented on apps/back/config/packages/doctrine.yaml
> +doctrine:
It is already on other PR.

2023-09-06 11:40 UTC, KevinArtus commented on apps/back/migrations/Version20230905094943.php
> +        $this->addSql('CREATE TABLE course_user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, username VARCHAR(180) NOT NULL, view
Again, use uuid

2023-09-06 11:40 UTC, KevinArtus commented on apps/back/migrations/Version20230905094943.php
> +        return '';
Please add description

2023-09-06 12:15 UTC, neghmurken commented on apps/back/src/Entity/Course.php
> +    private ?string $name = null;
Comme dit dans une autre PR par je sais plus qui, ce genre d'informations semblent obligatoires. Une Course ne devrait pas exister sans un ID et un nom.

2023-09-06 12:15 UTC, neghmurken commented on apps/back/src/Entity/Course.php
> +    private ?int $createdAt = null;
Même chose, ici, une fois l'objet instanciée, il devrait toujours avoir une date de création.

2023-09-07 14:12 UTC, NathanDid requested changes

2023-09-07 14:12 UTC, NathanDid commented on apps/back/src/Entity/Course.php
> +    private ?int $createdAt = null;
Et autant mettre une date plutôt qu'un entier !

2023-09-07 14:12 UTC, NathanDid commented on apps/back/src/Entity/Course.php
> +    public function getAuthor(): ?CourseUser
A priori un auteur ne peut pas être nul je crois !

2023-09-08 07:12 UTC, NathanDid approved these changes

2023-09-08 09:39 UTC, neghmurken approved these changes

2023-09-08 09:41 UTC, KevinArtus approved these changes

2023-09-08 09:46 UTC, merged